create table users(userid serial8 primary key, first_name varchar(32) not null, last_name varchar(64) not null, email varchar(200) not null unique, password varchar(100) not null, address1 varchar(100), address2 varchar(100), city varchar(100), state char(2), zip varchar(32), phone varchar(30), biography text, resume text);
create table bugs(bugid serial8 primary key, userid bigint references users, bugtext text, type integer, bugdate date);
create table forums(forumid serial8 primary key, title varchar(100), details text);
create table posts(postid serial8 primary key, parent bigint, forumid bigint references forums, subject varchar(200), post text, postdate date, userid bigint references users);
create table articles(articleid serial8 primary key, posted date, title varchar(100) not null, article text, userid bigint references users);
create table schedule(scheduleid serial8 primary key, starttime timestamp, endtime timestamp, details text, title varchar(100), userid bigint references users);
create table files(fileid serial8 primary key, filepath varchar(350), filename varchar(100), url varchar(1000));
create table emails(emailid serial8 primary key, subject varchar(300), body text);
create table notification(notifid serial8 primary key, userid bigint references users, emailid bigint references emails, send boolean);
create table trees(treeid serial8 primary key, title varchar(100) unique);
create table categories(treeid bigint references trees, catid serial8 primary key, parent bigint, title varchar(100), details text);
create table items(itemid serial8 primary key, tablename varchar(50), id bigint);
create table rights(rightid serial8 primary key, userid bigint, canadmin boolean, canread boolean, canwrite boolean, itemid bigint references items);
create table pages(pageid serial8 primary key, page varchar(600) unique);
create table catrel(catrelid serial8 primary key, itemid bigint references items, treeid bigint references trees, catid bigint);
create table polls(pollid serial8 primary key, question varchar(100), atext varchar(100), btext varchar(100), ctext varchar(100), dtext varchar(100), avotes bigint, bvotes bigint, cvotes bigint, dvotes bigint, votes bigint);
insert into users(first_name,last_name,email,password) values('Admin','istrator','admin','password');
insert into items(tablename,id) values('',0);
insert into rights(userid,canadmin,canread,canwrite,itemid) values(1,'t','t','t',1);
insert into emails(subject,body) values('New Article','#article_url#');
insert into emails(subject,body) values('New Forum Post','#forumpost_url#');
insert into emails(subject,body) values('New Event','#event_url#');
insert into trees(title) values ('Articles');
insert into items(tablename,id) values('trees',1);
insert into categories(treeid,parent,title,details) values (1,0,'General Articles','This category is for general articles');
insert into items(tablename,id) values('categories',1);
insert into polls(question,atext,btext,ctext,dtext,votes) values('What do you think of this site?','Incredible!','Good','Ok','Awful',0);